version: "1.0"

services:
  web:
    container_name: taylorswiftfan
    build: .
    command: python main.py
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]